export const AppName = 'Trillion CS';
export const Brand = {
  initial: '', // From Backend
  about: 'About ' + AppName,
  companyName: 'Trillion Credit Solutions Pte. Ltd.',
  companyStreet: '', // From Backend
  countryAddress: '', // From Backend
  LATITUDE: 1.2855852, // From Backend Chainatown
  LONGITUDE: 103.8442108, // From Backend Chainatown
  LATITUDE_DELTA: 0.01,
  companyEmail: 'info@trillioncredit.com.sg', // From Backend
  tel_phone: '+65 6222 0300', // From Backend
  weekDays: '', // From Backend
  weekEndDays: '', // From Backend
  holidays: '', // From Backend
};
const strings = {
  PageHeader: {
    signUp: 'Create New Account',
    login: 'Log In',
    forgotPassword: 'Forgot Password',
    home: 'Home',
    support: 'Support',
    faq: 'FAQ',
    contact: 'Contact',
    profile: 'Profile',
    resetPassword: 'Reset Password',
    confirmPassword: 'Confirm Reset Password',
    locateUs: 'Locate Us',
    speakus: 'Speak to us today',
    chooseLoan: 'Choose Loan',
    eligibilityCheck: 'Eligibility Check',
    loanCalculator: 'Loan Calculator',
    loan: 'Loan',
    myInfo: 'Myinfo',
    applicationForm: 'Application Form',
    personalInfo: 'PERSONAL INFORMATION',
    contactDetail: 'CONTACT DETAILS',
    propertyInfo: 'PROPERTY INFORMATION',
    empInfo: 'EMPLOYMENT INFORMATION',
    noa: 'NOTICE OF ASSESSMENT',
    cpfHistory: 'CPF Contribution History',
    financialCommitment: 'FINANCIAL COMMITMENT',
    Purpose_of_loan: 'PURPOSE OF LOAN',
    requirements: 'REQUIREMENTS',
    supportingDoc: 'SUPPORTING DOCUMENTS',
    consentDeclaration: 'Consent and Declaration',
    businessInfo: 'BUSINESS INFORMATION',
    rep_info: 'Representative Information',
    myLoan: 'My Loan',
    customerSupport: 'Customer Support',
    loanStatus: 'Loan Status',
    transactionHistory: 'Transaction History',
    paymentDetails: 'Payment Details',
    payment: 'Payment',
    settings: 'Settings',
    FAQ: 'FAQ',
    ABOUT_US: 'ABOUT US',
    PRIVACY_POLICY: 'PRIVACY POLICY',
    TERMS_AND_CONDITIONS: 'TERMS AND CONDITIONS',
    DECLARATION: 'DECLARATION',
  },
  PlaceHolders: {
    userid: 'Enter NRIC/FIN',
    password: 'Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password',
    nricFin: 'NRIC/FIN',
    search: 'Search',
    message: 'Message',
    annualIncome: 'Annual Income',
    anyAnotherLoan: 'Do you have another loan?',
    loanAmount: 'Loan Amount',
    loanTerms: 'Loan Terms',
    fullName: 'Full Name',
    principalName: 'Principal Name',
    aliasName: 'Alias Name',
    hanyuName: 'Hanyu Pinyin Name',
    hanyuAliasName: 'Hanyu Pinyin Alias Name',
    phone_no: 'Phone No',
    mobileNumber: 'Mobile Number',
    tel_number_home: 'Home Telephone Number',
    tel_number_office: 'Office Telephone Number',
    email: 'Email',
    maritalStatus: 'Marital Status',
    gender: 'Gender',
    sex: 'Sex',
    dob: 'Date of Birth',
    residentialStatus: 'Residential Status',
    countryOfBirth: 'Country of Birth',
    passType: 'Pass Type',
    passStatus: 'Pass Status',
    passExpiryDate: 'Pass Expiry Date',
    empSector: 'Employment Sector',
    id_type: 'ID Type',
    id_number: 'ID Number',
    nationality: 'Nationality',
    race: 'Race',
    block: 'Block',
    street: 'Street',
    unitNumber: 'Unit Number',
    building: 'Building',
    regAddress: 'Registered Address',
    postalCode: 'Postal Code',
    altAddress: 'Alternate Address',
    HDB_type: 'Type of HDB',
    housing_type: 'Type of Housing',
    country: 'Country',
    countryCode: 'Country Code',
    propertyType: 'Property Type',
    propertyOwnType: 'Property Ownership Type',
    HDB_ownership_address: 'HDB Ownership - Address ',
    HDB_dwelling: 'HDB Ownership - Type of HDB Dwelling',
    privateResidential: 'Ownership of Private Residential Property',
    yearOfAssessment: 'Year of Assessment',
    assessment_type: 'Category',
    tax_clearance: 'Tax Clearance',
    assessableIncome: 'Assessable Income',
    employment: 'Employment',
    trade: 'Trade',
    rent: 'Rent',
    interest: 'Interest',
    amount: 'Amount',
    paid_month: 'Paid for Month',
    paid_on: 'Paid On',
    contributionTotal: 'Contribution Total',
    empStatus: 'Employment Status',
    month1Income: 'Month 1 Income',
    month2Income: 'Month 2 Income',
    month3Income: 'Month 3 Income',
    occupation: 'Occupation',
    empName: 'Name of Employer',
    empAddress: 'Address of Employer',
    empSpecialization: 'Specialization',
    empPosition: 'Position',
    empLength: 'Length of Employment',
    empPaydaySchedule: 'Payday Schedule',
    empPaymentSchedule: 'Payment Schedule',
    specificDate: 'Specific Date',
    date: 'Date',
    ordinaryAccount: 'Ordinary Account',
    specialAccount: 'Special Account',
    medisaveAccount: 'Medisave Account',
    retirementAccount: 'Retirement Account',
    loanNumbers: 'Number of outstanding licensed money lenders loan',
    totalLoanAmount: 'Total amount of outstanding licensed money lender loans',
    bankCreditLoansNumbers:
      'Number of outstanding bank loans and credit card spending',
    totalBankCreditLoans: 'Total amount of bank loans and credit card spending',
    purpose_of_loan: 'Purpose of Loan',
    inputAmount: 'Input Amount',
    inputNumber: 'Input Number',
    numberOfLoan: 'Input Number of Loans',
    idProofFront: 'ID Proof Front',
    idProofback: 'ID Proof Back',
    addProof: 'Address Proof',
    payslipMonth: 'Payslip Month',
    companyName: 'Company Name',
    Obligation: 'Obligation Type',
    doInc: 'Date of Incorporation',
    incNumber: 'Incorporation Number',
    businessType: 'Business Type',
    businessAddress: 'Business Address',
    resPropertyType: 'Residencial Property Type',
    companyNationality: 'Nationality of Company',
    companyCountry: 'Country of Company',
    companyCountryCode: 'Country Code of Company',
    businessContactNo: 'Business Contact Number',
    rep_name: 'Representative Name',
    rep_id_type: 'Representative UID Type',
    rep_address: 'Representative Address',
    rep_acra_position: 'ACRA Position Type',
    rep_contactNo: 'Representative Contact Number',
    docProofType: 'Document Proof Type',
    loan_acc: 'Loan Account',
    googleLink: 'Google Review Link',
    branch: 'Branch',
    branch_name: 'Branch Name',
  },
  LoanTypes: {
    personalLoan: 'Personal Loan',
    businessLoan: 'Business Loan',
    foreignerLoan: 'Foreigner Loan',
    paydayLoan: 'Payday Loan',
    bridginLoan: 'Bridgin Loan',
    dcLoan: 'Debt Consolidation Loan',
  },
  Title: {
    termsCondition: 'By this, you agree to ' + AppName + ' Singapore’s',
    dontHaveAcc: "Don't have an account?",
    emailAdd: 'Email Address',
    forgotPinPlaceholder: 'Enter your mobile number',
    pinFingerPrint: 'Create New PIN',
    verificationCode: 'Enter Verification code',
    noEmailRegisterd: 'No email address registered with us',
    verificationCodeDetail:
      'We have sent verification code\n on your number - ',
    resendVerificationCode: 'Resend Verification code',
    pinDetail: 'Create your new PIN Code',
    confirmPincode: 'Confirm PIN code',
    loginWithFingerPrint: 'Login with fingerprint',
    congratulations: 'Congratulations!',
    anyLoan: 'Do you have any existing loan?',
    addLoanNo: 'Add Loan ID',
    loanId: 'Loan ID',
    addAnotherLoanNo: '+ Add Another ID',
    getLoan: 'Get Loan',
    myLoan: 'My Loan',
    history: 'My Transaction',
    payment: 'Payment',
    security: 'Security',
    resetPin: 'Reset PIN',
    activateFingerprint: 'Fingerprint / Face Unlock ',
    placeholderCurrentPin: 'Input your current PIN Code',
    newPin: 'Create your new PIN Code',
    confirmPin: 'Confirm PIN Code',
    placeholderCurrentPassword: 'Input your current Password',
    createPassword: 'Create your new Password',
    FIN_no: 'FIN Number',
    FIN: 'FIN',
    receipt: 'Input receipt number',
    receiptNo: 'Receipt Number',
    paymentProcess: 'Payment Process',
    contactTitle: 'Speak to us today',
    messages: 'Messages',
    locateUs: 'Locate Us',
    telNo: 'Tel. Number',
    officeHours: 'Office Hours',
    thankyou: 'Thank You',
    feedback: 'Enjoying ' + AppName + ' App?',
    feedback2: 'How would you rate our service?',
    maybeLater: 'Maybe Later',
    changeMobileNo: 'Change Mobile Number',
    moneyAmount: 'How much do you need?',
    selectPayScale: 'Select your Payment Schedule',
    chooseTerm: 'Choose your loan term',
    expectedLoanDate: 'When do you want the loan?',
    date: 'Select Date',
    loanAmountText: 'Loan Amount',
    amount: 'Enter your Amount here',
    defaultAmount: '0',
    paySchedule: 'Payment Schedule',
    estimateDate: '(Estimate for every 14 days)',
    totalAmount: 'Total repayment',
    interestrate: 'Interest rate',
    interestAddedText: '(Interest included)',
    selectLoan: 'Select loan',
    amountPaid: 'Amount Paid',
    headerDate: 'Date of Payment',
    headerTime: 'Time',
    selectTime: 'Select Time',
    payslip: 'Payslip Month',
    consent: 'Consent and Declaration',
    success: 'Success',
    aboutVersion: 'Version ',
    appVersion: 'V',
    incomePlaceholder: 'Add Month',
    month1Income: 'Month 1 Income',
    month2Income: 'Month 2 Income',
    month3Income: 'Month 3 Income',
    empStatus: 'Employment status',
    dob: 'Date of Birth',
    gender: 'Gender',
    genderPlaceholder: 'Select Gender',
    selectIdType: 'Select ID Type',
    selectRepayment: 'Select Repayment',
    idType: 'ID Type',
    idNumber: 'Incorporation Number',
    block: 'Block',
    street: 'Street',
    unitNumber: 'Unit No.',
    building: 'Building',
    postalCode: 'Postal Code',
    country: 'Country',
    countryCode: 'Country code',
    loanAcNo: 'Loan A/C No:',
    totalSumPaid: 'Total sum paid:',
    loanDate: 'Date:',
    totalOSamount: 'Total OS Amount',
    myInfoTerms:
      'Clicking the “I Agree” button permits this digital service to retreive your data based on the ', // message
    selectLoanAcc: 'Select Loan Account',
    transactionNo: 'Receipt Id',
    SelectRepayment: 'Select Repayment',
    deleteAccount: 'Delete Account',
    licenseNo: 'License No',
    working_hours: 'Working Hours',
  },
  Messages: {
    loanApproved: 'Your loan application has been approved',
    loanDeclined: 'Your loan application has been declined',
    pinChanged: 'Your PIN Code has been changed',
    contactThanksTxt: 'Thank you for contacting us',
    paymentThanks: 'Thank you for your payment!',
    reachTime: 'We will get back to you within 24 hours',
    paymentReachTime: 'Your payment will be updated within 3 working days. ',
    rateText: 'Reccomend us to other by rating us \n on the App Store',
    changedMobileText: 'Your mobile number has succesfully changed',
    submittedApplication: `Your application has been submitted succesfully`,
    contactSoonText: AppName + ' team will contact you soon!',
    noLoan: `You haven't applied any loan yet`,
    addExistingLoan: 'Add existing loan ID',
    existingLoan: 'ADD EXISTING LOAN',
    Successmsg: 'Success! Your data has been retrieved successfully',
    NOnoti: `You don't have any notifications`,
    loginAgain: 'Please login again',
  },
  ButtonTitle: {
    login: 'Log In',
    loginMyAc: 'LOG IN WITH ACCOUNT',
    registerWith: 'REGISTER WITH US',
    signUpMyAc: "Don't have an account?",
    logout: 'Log Out',
    register: 'Register',
    confirm: 'Confirm',
    appRate: 'Rate Us',
    sendEmail: 'Send Email',
    back: 'Back',
    cancel: 'Cancel',
    ok: 'Ok',
    done: 'Done',
    myInfoLogin: 'Retrieve Myinfo with singpass',
    fillUpForm: 'Fill up the form manually',
    edit: 'Edit',
    save: 'Save',
    backtoLogin: 'Back to Login',
    next: 'Next',
    submit: 'Submit',
    backSupport: 'Back to Home',
    rateBtn: 'Yes, Rate it Now',
    noThanks: 'No, Thanks',
    apply: 'Apply Now',
    paymentReceipt: 'Payment Receipt',
    backHome: 'Back to Home',
    applyLoan: 'Apply Loan',
    continuetoNext: 'Continue filling other information',
    calculate: 'Calculate',
  },
};

const alerts = {
  LOGOUT_MESSAGE: 'Are you sure to logout from the application?',
  EXIT_TITLE: 'Exit App',
  EXIT_MESSAGE: 'Are you sure to exit the application?',
};

export {strings, alerts};
